name: Validate Homey App
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test

  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
